name: Robot Framework Test on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 13 * * *'  
  workflow_dispatch:

jobs:
  cypress-run:
    name: Run Robotframework on Windows 
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          node-version: 22.3.0

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r JamtanganOutlineGithub/requirements.txt

      # Step 4: Run Robot Framework tests
      - name: Run Robot Framework tests
        run: |
          robot --outputdir results JamtanganOutlineGithub/features/

     # hanya menjalankan tes dengan tag smoke:
     # - name: Run Robot Framework smoke tests
     #   run: |
     #   robot --outputdir results --include smoke tests/

    #  Jika ingin mengecualikan tes dengan tag tertentu, misalnya slow:
     #  - name: Run Robot Framework tests (excluding slow tests)
     #    run: |
     #   robot --outputdir results --exclude slow tests/

      # Step 5: Upload test results
      - name: Upload Robot Framework results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
